name: "Seiden EVO Bridge"
version: "0.3.1"
slug: "seiden_evo_bridge"
description: "Integra leitores EVO Facial ao Home Assistant com motor de ocupação e monitoramento de disponibilidade"
url: "https://github.com/eduseiden/Seiden-HA"

startup: services
boot: auto
init: false

arch:
  - amd64

host_network: true
hassio_api: true
homeassistant_api: true
hassio_role: default

options:
  poll_interval: 2
  request_timeout: 5
  max_retry_interval: 300
  log_level: "INFO"

  ha_event: "seiden_presence"
  reader_offline_event: "seiden_reader_offline"
  reader_online_event: "seiden_reader_online"

  readers:
    - name: "Entrada"
      ip: "192.168.4.157"
      password: "1234"
      direction: "in"

schema:
  poll_interval: int
  request_timeout: int
  max_retry_interval: int
  log_level: list(DEBUG|INFO|WARNING|ERROR)

  ha_event: str
  reader_offline_event: str
  reader_online_event: str

  readers:
    - name: str
      ip: str
      password: password
      direction: list(in|out)
