name: "Seiden EVO Bridge"
version: "0.2.1"
slug: "seiden_evo_bridge"
description: "Integra leitores EVO Facial ao Home Assistant com motor de presença."
startup: services
boot: auto
init: false
host_network: true
hassio_api: true
homeassistant_api: true
arch:
  - amd64

options:
  poll_interval: 2
  ha_event: "seiden_presence"
  readers:
    - name: "Entrada"
      ip: "192.168.4.157"
      password: "1234"
      direction: "in"

schema:
  poll_interval: int
  ha_event: str
  readers:
    - name: str
      ip: str
      password: password
      direction: list(in|out)
